### ISSUE TITLE
Stop Spamming People

### ISSUE THREAD

**Issue by jamiebuilds** [reactnative/reactnative.com#1]

**Comment by reactnative** [comment]
Sorry to hear, but don't worry, you won't get any other mail.

Bests.

**Comment by jamiebuilds** [comment]
Don't send it to others either.

**Comment by jamiebuilds** [comment]
I hope this site fails miserably.

**Comment by reactnative** [comment]
That would be one sending as stated in the mail.
We hope that providing visibility to, mostly, open source projects would be beneficial for someone (either that he wants to learn or getting noticed).

(for context)

```
Hi,
we've noticed you're following the React Native project on GitHub
https://github.com/facebook/react-native

we're sending you this one time mail to inform you that we're building a community website about React Native at the address
http://www.reactnative.com
and tweeting about it at
https://twitter.com/UseReactNative

You might be interested in checking it out, if not, you won't hear from us again, we promise!

Thanks for your time.
```

**Comment by jamiebuilds** [comment]
Reported to GitHub, hopefully they terminate your account.

**Comment by reactnative** [comment]
We hope not, mail's content is attached to this issue.
